name: Deploy to Cloudflare Pages

on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
    inputs:
      directory:
        required: true
        type: string
      project-name:
        required: true
        type: string
      account-id:
        required: true
        type: string
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build site
        run: bun run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ inputs.account-id || 'your-account-id' }}
          projectName: ponzi-site
          directory: ${{ inputs.directory || 'dist' }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref || github.ref_name }}
          production: ${{ github.ref == 'refs/heads/main' }}
